# Generated by Django 2.2.3 on 2019-07-21 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitkat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_of', to='kitkat.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('ENG', 'Engineering'), ('PROD', 'Product'), ('PS', 'Partner Success'), ('SALE', 'Sales')], max_length=50),
        ),
    ]
