# Generated by Django 2.2.3 on 2019-07-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitkat', '0002_auto_20190721_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
