# Generated by Django 2.2.3 on 2019-07-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitkat', '0003_request_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
