# Generated by Django 2.2.3 on 2019-08-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitkat', '0004_request_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
